Repository JosephJamesCoop/the-allergy-free-kitchen, pull requests merged in 2022-02, with the labels that each got.

#5 Feature/models
  controllers/api/index.js
  controllers/api/recipe-routes.js
  controllers/api/user-routes.js
  controllers/api/vote-routes.js
  controllers/index.js
  models/Recipe.js
  package.json
Labels: enhancement

#11 Feature/models
  controllers/api/recipe-routes.js
  models/Recipe.js
Labels: enhancement

#14 Feature/recipe profile
  controllers/allergy-routes.js
  controllers/api/recipe-routes.js
  controllers/index.js
  controllers/recipe-profile-routes.js
  models/Allergy.js
  models/Recipe.js
  public/javascript/recipe-profile.js
  views/partials/ingredients.handlebars
  views/partials/single-recipe-description.handlebars
  views/recipe-profile.handlebars
Labels: bug, enhancement

#21 Feature/navbar
  controllers/homepage-routes.js
  controllers/userprofile-routes.js
  public/javascript/allergen-filter.js
  public/javascript/login.js
  public/stylesheets/style.css
  views/layouts/main.handlebars
  views/partials/ingredients.handlebars
  views/partials/single-recipe-description.handlebars
  views/recipe-profile.handlebars
Labels: enhancement

#22 Feature/add r zulu
  controllers/api/recipe-routes.js
  controllers/recipe-profile-routes.js
  controllers/userprofile-routes.js
  models/Allergy.js
  models/Recipe.js
  models/index.js
  package-lock.json
  package.json
  public/javascript/add-recipe.js
  public/javascript/add-vote.js
  public/javascript/allergen-filter.js
  public/javascript/edit-post.js
  public/javascript/login.js
  public/javascript/logout.js
  public/javascript/recipe-profile.js
  views/add-recipe.handlebars
  views/edit-post.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
Labels: bug, enhancement

#23 Bug fix for recipe-profile view
  models/Recipe.js
Labels: bug

#25 removed js files from where not needed and casuing errors
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/partials/allergens.handlebars
  views/userprofile.handlebars
Labels: bug

#26 sending session variable to recipe-card partial for upvotes
  views/homepage.handlebars
  views/partials/recipe-description.handlebars
  views/userprofile.handlebars
Labels: bug

#32 Merging Develop into Main
  .gitignore
  README.md
  config/connection.js
  controllers/allergy-routes.js
  controllers/api/index.js
  controllers/api/recipe-routes.js
  controllers/api/user-routes.js
  controllers/api/vote-routes.js
  controllers/homepage-routes.js
  controllers/index.js
  controllers/recipe-profile-routes.js
  controllers/userprofile-routes.js
  db/schema.sql
  db/seeds.js
  models/Allergy.js
  models/Recipe.js
  models/User.js
  models/Vote.js
  models/index.js
  package-lock.json
  package.json
  public/icons/Celiac.png
  public/icons/Dairy.png
  public/icons/Nut.png
  public/icons/Shellfish.png
  public/icons/Soy.png
  public/icons/Vegetarian.png
  public/javascript/add-recipe.js
  public/javascript/add-star.js
  public/javascript/add-vote.js
  public/javascript/allergen-filter.js
  public/javascript/edit-post.js
  public/javascript/login.js
  public/javascript/logout.js
  public/javascript/recipe-profile.js
  public/javascript/recipes.js
  public/javascript/signUp.js
  public/stylesheets/style.css
  server.js
  utils/auth.js
  utils/helpers.js
  views/add-recipe.handlebars
  views/edit-post.handlebars
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/partials/allergens.handlebars
  views/partials/allergy-chart.handlebars
  views/partials/ingredients-instructions.handlebars
  views/partials/ingredients.handlebars
  views/partials/recipe-description.handlebars
  views/partials/single-recipe-description.handlebars
  views/recipe-profile.handlebars
  views/signUp.handlebars
  views/userprofile.handlebars
Labels: enhancement

#34 adding heroku deployed link and inflection badge
  README.md
Labels: enhancement
